# Generated by Django 3.1 on 2020-09-28 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tregistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('second_name', models.CharField(blank=True, max_length=255, null=True)),
                ('user_name', models.CharField(blank=True, max_length=500, null=True)),
                ('email', models.CharField(blank=True, max_length=500, null=True)),
                ('country_code', models.IntegerField(blank=True, default=0, null=True)),
                ('phone_number', models.IntegerField(blank=True, default=0, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('native_laguage', models.CharField(blank=True, max_length=500, null=True)),
                ('specialization', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.TextField(blank=True, max_length=5000, null=True)),
                ('sample_essay', models.FileField(blank=True, max_length=255, null=True, upload_to='Upload_files/%Y%m%d/')),
                ('selfie', models.FileField(blank=True, max_length=255, null=True, upload_to='Upload_files/%Y%m%d/')),
            ],
        ),
    ]
