# Generated by Django 3.1 on 2020-09-26 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(blank=True, max_length=255, null=True)),
                ('pages', models.IntegerField(blank=True, default=0, null=True)),
                ('style', models.CharField(blank=True, max_length=255, null=True)),
                ('subject', models.CharField(blank=True, max_length=500, null=True)),
                ('amount', models.IntegerField(blank=True, default=0.0, null=True)),
                ('instructions', models.TextField(blank=True, max_length=5000, null=True)),
                ('uploads', models.FileField(blank=True, max_length=255, null=True, upload_to='Upload_files/%Y%m%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UploadFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.FileField(blank=True, max_length=255, null=True, upload_to='Upload_files/%Y%m%d/')),
            ],
        ),
    ]
